USBHost_t36.h, examples/Mouse/Mouse.ino, joystick.cpp
Had to increase size of HID report to 512.
Allow HAT to work 10039
Mouse Example prints out Z, Rz, Ry, Rx and Hat values
=> PS4 support

hid.cpp
There is an issue with the extra items added to the report after the main known items.
Problem was HID report descriptor does something like:
Usage Page; Desktop  (01)
Usage: 01  (Pointer)
Count xxx
Problem is the Usage values below 0x20 appear to have some other standard meaning.   Which you can see in
http://www.usb.org/developers/hidpage/Hut1_12v2.pdf
So current fix is to ignore Usage values passed in < 0x20...
Appears to fix PS3 Right joystick
=> PS3 - Right Joystick does not work

USBHost_t36.h, antplus.cpp, enumeration.cpp, examples/Mouse/Mouse.ino, hid.cpp, hub.cpp, keyboard.cpp, memory.cpp, midi.cpp, serial.cpp
instead of having each HUB have 7 buffers, which can eat up space.  We have each main object contribute currently one string buffer, which than when we initialize a Device_t we try to allocate one for it, likewise we release it when the Device is released.
Hopefully less memory needed.
Also updated such that the HIDInput classes can not retrieve these strings.
Changed test program to now also have list of HIDInput objects and when I detect a new one, I again print out info on it...
Paul - Let me know if you want things changed here like such they simply return a const uint8_t * to the string, or should the user pass in buffer, size which we copy into.
=> String buffers - Devices contribute buffers

USBHost_t36.h, ehci.cpp, examples/SerialTest/SerialTest.ino, keyboard.cpp, serial.cpp
Paul, 
I believe I have at some more Serial devices working.  
I was earlier able to talk to some CDCACM devices.  This included both an USB2AX device (Atmega 32u2 using Lufa) as well as to talk to a Teensy.  Tried a T3.2 both as Serial only as well as Serial Plus other USB types. 
Now was able to talk to Prolific PL2303 device - Which I was able to configure to 115200 and have it talk to an Lynxmotion SSC-32 servo controller and ask it for it's version.
We probably may need to updated the VID:PID testing to allow more combinations like the Unix driver does.   
Also may need to maybe setup multiple files or the like to handle the differences between different serial types. 
Let me know what you think
=> Cdcacm serial

USBHost_t36.h, examples/Mouse/Mouse.ino, keyboard.cpp, keywords.txt
The first gigabyte fix, was to always force the keyboard into boot protocol mode, which appeared to work well for all of the keyboards I tried.
Unforationally it caused issues with some wireless keyboard/mouse combo packages, including some logitech and some microsoft keyboards.
This version instead, I created a list (currently only one vendor id), of vendor id:product id, that need to be forced into boot mode.  Knowing that if there is one keyboard vendor with this N key rollover feature, there are probably others.  So while this list can be expanded, this requires users to update library.  So added a method forceBootProtocol method to keyboard class that allows the user to try it out without needing to update the library sources.
The mouse test program has example of either setting it …
=> Now only optionally force keyboard into boot protocol mode

ehci.cpp
For files of length 1<<14 there should be no 'next', as all data are transferred in one transfer
=> Correct queue_Data_Transfer

midi.cpp
Fixed race condition in midi transmit that could happen with heavy write traffic, in combination with reading. This would lock up the usb host device, when it happened. Disabling interrupts around access to the data queue in write_packed() matches what read() is already doing, so this seems like the correct solution.
=> fixed race condition in midi transmit

USBHost_t36.h, examples/Test/SerialTest/SerialTest.ino, keywords.txt, serial.cpp
This delta originated to do the work similar to what was done
for the MIDI code base and support two versions of the object.
All of the code was renamed to a new base class USBSerialBase
which has everything, except the main buffer.
Two sub-classes were made that the only difference is the size of the
buffer to hold all of the USB RX and TX information.
This started off to try to support an FT2232H device which transers
512 bytes at a time instead of what most of our devices were transfering
which is 64 bytes.
While doing this, I found that we have a similar issue with the T4.x
boards which now transfer 512 bytes as well and our Serial object would
not handle it.
So there are two sublasses:
```
USBSerial - for those up to 64 byte transfers
USBSerial_BigBuffer - for up to 512 bytes
``` …
=> USBSerial_BigBuffer - T4.x (multi devices)

examples/HIDDeviceInfo/HIDDeviceInfo.ino, examples/HIDDeviceInfo/HIDDumper.cpp, examples/HIDDeviceInfo/HIDDumper.h, examples/HIDDeviceInfo/USBDeviceInfo.cpp, examples/HIDDeviceInfo/USBDeviceInfo.h
USB HID Info Example sketch
There have been many cases where users plug in some new HID device, which we do not currently support, and we have very little information to go on.
So this sketch simply tries to print out the HID information for each message received from the device.
It has a simple sub-class of the USBHIDInput class, which prints out the data. Which could give us a lot of data on adding support to the library, plus shows how users can write their own sub-class for their own devices.
=> Hid device info example

MassStorageDriver.cpp, USBHost_t36.h, examples/mscTesting/mscTesting.ino, utility/msc.h
Hi Paul,
I finally got the nerve to submit the latest version of the MSC driver for inclusion into USBHost_t36.
All I added was the "MassStorageDriver.cpp" and modified "msc.h" files plus one test sketch.
"MassStorageDriver.cpp" was added to the main directory, "msc.h" now contains only the needed parts of "MassStorage.h" (not included). The contents of "msc.h" were added to "USBHost_t36.h". I put "msc.h" file in the utility directory. I am not sure if this is the proper place to put it. the only ".h" files I saw in the main directory were def.h files.
An example sketch, "mscTesting.ino" was added to the examples directory.
Thanks
=> Addition of Mass Storage Driver to this library

SerEMU.cpp, USBHost_t36.h, hid.cpp, keywords.txt, library.properties, rawhid.cpp, serial.cpp
I was working on some other USBHost extensions and found I needed debug information that was
being generated by a Teensy plugged into the USB host port that was output using Serial Emulation
to be available.  Likewise I wanted the ability to feed data back to that other Teensy.
So I decided to create USBHost_t36 implementation to handle the USB types that include Serial Emulation
USBSerialEmu class.
The USBSerialEmu code was based on the USBSerial code as well as RAWHID.  I found that there was a bug
in the Receiving of data that was sent by the remote SEREMU output, I would miss the first character
Fixed.
USBSerial fixed same bug in reading first character
@PaulStoffregen  - This stuff was extracted from my MTP Device USB Host code, which is currently only in a test state.  
I do have a …
=> USBSerial fix add USBSerialEmu

MassStorageDriver.cpp, USBHost_t36.h
Paul,
I have updated the msProcessError() method so that external processing sense codes can be parsed and displayed as descriptive error strings using a sense key, additional sense codes and additional sense code qualifiers. I also modified msReset() and msGetMaxLun() methods to use an interface number with wIndex in mk_setup(). In an email I received hathach mentioned that wIndex should be set to an interface number. So far with the bNumInterfaces at 1 and bInterfaceNumber at 0. I'm not sure if this only applies to  just the control pipe. Link is here:
[https://github.com/PaulStoffregen/USBHost_t36/pull/42#discussion_r583694595](url).
=> Updates for MassStorageDrivver.cpp and USBHost_t36.h

MassStorageDriver.cpp, USBHost_t36.h
This add bInterfaceNumber member to use with msReset() and msGetMaxLun() as follow up to #55 . The bInterfaceNumber is part of interface descriptors and can be saved while `claim()` interface to be used with reset and get maxlun later on. It is not actually the case where interface is passed by application, sorry for not being clear enough on the comment at https://github.com/PaulStoffregen/USBHost_t36/pull/42#discussion_r583694595 
This PR is tested with single MSC class as well as composite device that has CDC as first interface (0,1) and msc as 2nd interface (2)
=> Improve MSC Reset() and GetMaxLun()

MassStorageDriver.cpp, USBHost_t36.h
Experiment with the VolumeName and other MSC example scketchs in the
UsbMSCFat project, in order to get the free space faster!
This included adding timeouts as sometimes the host does not fully respond.
Try to keep the code from hanging if for some reason we don't get enough messages back from host...
=> Experiment - Add a msReadSectorsWithCB function

bluetooth.cpp
@PaulStoffregen and @mjs513
Forgot to disable the DEBUG_BT define so receive debug output...
Turned it off and verified it compiled for both T3.6 and T4.1
=> Turn Bluetooth Debug off by default

USBHost_t36.h, serial.cpp
As per the forum Thread: https://forum.pjrc.com/threads/67677-Kurt-USB_HOST-(T4-1)-Serial-hardware-handshake
Frank wanted the ability to write a pass through sketch that would allow him to program either an
Arduino UNO or an ESP32 that was plugged into the USBHost.
Adding support for this helped to uncover a few other issues with the code, like turned out there
was/is an long standing bug with the read code that it was reading the wrong byte from the queue.
He has another PR that addressed this.
This PR has both that fix as well as fixing Peek.
To support the reprogramming, needed to add support for allowing the host code to control both the DTR and
the RTS signals. Likewise it is needed to allow the code to change the baud rates.  This part uncovered an issue with the CP2102 code that …
=> USBSerial support for setting DTR/CTS

.gitignore, USBHost_t36.h, bluetooth.cpp, examples/Bluetooth/JoystickBT/JoystickBT.ino, hid.cpp, joystick.cpp
With previous verison was able to get the Sony PS4 to work
but not most of the clones including one by Voyee.
Found that if I disabled some code that was put in for PS4
to force our code to initiate the bind operation.  Then the
voyee worked... Found later that in the USB Host Shield 2
that they detected the underlying class number and only if
0x2508 did it initiate the bind... voyee is 0x508.  So both
now appear to want to bind.
Changed the JoystickBT sketch to allow you to hit enter in debug
window and switch PS4 from long view to short view of data
Also found information on PS4 binding and some Python code that
allowed PS4s to bind without having to do it through BT.  So added
code like we have for PS3 that allows you to first have
the BT dongle in, then plus in PS4, and then hold …
=> Bluetooth PS4 sketch and supporting some clones

examples/KeyboardForeward/KeyboardForeward.ino
Hi @PaulStoffregen 
Since I have read several requests for a keyboard forwarder functionality in USB Host, thought maybe I would try building a version.
This example sketch can be configured to simply print out the debug information, similar tot he mouse.ino example sketch.  For a keyboard. 
But if you build with a USB Type that includes keyboard, it will try to forward everything from the keyboard to the Teensy Host... 
For normal like keys, it captures them using the capture RAW data code in USBHost code and sends them to the PC by calling keyboard.press with the scan code | 0xF000  (likewise for release).
It also looks at the modifier data and if changed updates it for Keyboard.
Also it checks to see if keyboard_leds changed and if so it tells the keyboard attached to update to the new …
=> Keyboard foreward

USBHost_t36.h, hid.cpp
@PaulStoffregen  - 
I simply added second buffer and input transfer and
the speed for Glorious Mouse 1000hz went up from
about 500hz to about 900+...
Also appears to resolve the issue that mcrc was reporting...
Not sure if you want it quick and dirty, with extra buffer, of if instead try to split current buffer in half as the buffers are 64 bytes long and in this case I think the messages are only 8 bytes...
=> Some Fast devices like 1000hz mouse don't run full speed

enumeration.cpp
This change is to support more devices.  Even my 20 year old BRC2000 has a descriptor size of almost 1k.  iConnectivety devices typically have descriptors over 1k.  By implementing this change you will avoid repetitive posts in the forums about people have issues connecting their class compliant devices to the host port.
=> Increased the descriptor buffer to 2k

library.properties
In the PlatformIO registry, the library is stuck at 0.1 because that's the only version this library was ever at (https://registry.platformio.org/libraries/paulstoffregen/USBHost_t36/versions).
Bumping up the version to trigger a recrawl for PlatformIO (and possibly Arduino IDE library managers).
=> Bump version

.gitignore, MassStorageDriver.cpp, USBFilesystemFormatter.cpp, USBFilesystemFormatter.h, USBHost_t36.h, examples/Storage/DriveInfoAll/DriveInfoAll.ino
@PaulStoffregen 
@mjs513  and myself have been extending the beta1 code to add some additional stuff.  We still need to go through and rework some of the examples and test more, but thought I would go ahead and issue a PR with current WIP as to give you a head start on seeing what has changed so far: 
First pass to add the functionality we were using with the previous
integration pass and work toward beta 2...
Still retaining some support for the Beta1 way of starting up a filesystem:
but added USBFilesystem::end() which closes the file system allows you to reuse the object.
Added bool operator to USBFilesystem know if object is valid.
Added USBFSBase class that works like hid class or the like, that USBFilesystem derives from. Which allows us to have
multiple Filesystem implementations. …
=> Start enumeration support plus

hid.cpp, joystick.cpp, keyboard.cpp, mouse.cpp
There was an issue with supporting some of the more advanced keyboards where
we thought we needed to claim more topusages in the generic desktop HID page
So, we were claiming too many which causes issues where it was claiming ones that
should be claimed by Mouse or Joystcik.
So removed the extras claiming code.
Also comment out some debug outputs that were left in earlier and also 
updated a few of the output comments to see who was claiming what.
But these are also commented out.
=> Keyboard should not claim topusages meant for Mouse or Joystick

MassStorageDriver.cpp, USBHost_t36.h, examples/Storage/DriveInfo/DriveInfo.ino, examples/Storage/ListFiles/ListFiles.ino, examples/Storage/WavFilePlayerUSB/WavFilePlayerUSB.ino, examples/Storage/WavFilePlayerUSB/play_usb_wav.cpp, examples/Storage/WavFilePlayerUSB/play_usb_wav.h
Fixes #102
Several of the examples were not updated to work with the now automatic enumeration of partitions code.
I removed a few more pieces of the old manual code and updated the examples to reflect this.
I also updated the wave player example to play all of the wave files in the root directory of the storage instead of some fixed named ones.
@pr8x @mjs513 @wwatson4506 
Hopefully did not mess anything up. Pretty straight forward.
=> Update Storage Examples

MassStorageDriver.cpp, utility/msc.h
Found "msReset()" was causing certain USB flash drives to fail to initialize and/or read/write. Several SanDisk devices have been proven to fail because of this.This could possibly be due to clearing default power on settings. Commented out "msReset()". Also extended the two timeouts in "msc.h" to 5000ms each. Needed for some SSD drives and SD card readers.
=> Fix certain USB flash drive usage failures. 

antplus.cpp
This fix was suggested by HRBF here: https://forum.pjrc.com/threads/43110-Ant-libarary-and-USB-driver-for-Teensy-3-5-6?p=272817&viewfull=1#post272817 . I noticed the same lockup when I attempted to run the AntPlus.io as well. This fixed the issue for me as well.
=> Fix locking up when using AntPlus.io example on a Teensy 4.1

serial.cpp
I used this library to connect a Teensy to a Yaesu FT-891 amateur radio transceiver.  It would not see the radio until I added the new line with the PID for the CP2105 chip.
=> Added new PID for Silex CP210X.

USBHost_t36.h
Not defining or marking a virtual function _pure virtual_ (`=0`) is actually UB in C++:
> C++03 Standard: 10.3 Virtual functions [class.virtual]
> 
> A virtual function declared in a class shall be defined, or declared pure (10.4) in that class, or both; but no diagnostic is required (3.2).
This was actually causing obscure linker issues in debug mode (see [here](https://forum.pjrc.com/threads/73333-DEBUG-undefined-reference-to-vtable-for-USBDriver))
=> Mark functions as properly pure virtual
